services:
  db:
    restart: always
    image: docker.io/postgres:18
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ravyn"
    command: >-
        --jit=false

    ports:
      - "127.0.0.1:5432:5432"

  mongodb:
    restart: always
    image: docker.io/mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: mongodb
    ports:
      - "127.0.0.1:27017:27017"

  redis:
    restart: always
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"

  mongo-express:
    image: docker.io/mongo-express
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
