#!/bin/sh -e

if [ -d 'dist' ] ; then
    rm -r dist
fi
if [ -d 'site' ] ; then
    rm -r site
fi
if [ -d 'site_lang' ] ; then
    rm -r site_lang
fi
if [ -d 'docs/generated' ] ; then
    rm -r docs/generated
fi
if [ -d '.cache/docs-sites' ] ; then
    rm -r .cache/docs-sites
fi
for path in docs/*/generated docs/*/site docs/*/.generated docs/*/.site ; do
    if [ -d "$path" ] ; then
        rm -r "$path"
    fi
done
if [ -d 'htmlcov' ] ; then
    rm -r htmlcov
fi
if [ -d 'ravyn.egg-info' ] ; then
    rm -r ravyn.egg-info
fi
if [ -d '.hypothesis' ] ; then
    rm -r .hypothesis
fi
if [ -d '.mypy_cache' ] ; then
    rm -r .mypy_cache
fi
if [ -d '.pytest_cache' ] ; then
    rm -r .pytest_cache
fi
if [ -d '.ruff_cache' ] ; then
    rm -r .ruff_cache
fi
